version: "3.9"
services:
  fastapi:
    build: .
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload


  mongo:
    image: mongo
    container_name: vehicle_allocation_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: